//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lanuage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lanuage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend.resources.lanuage", typeof(lanuage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.Status.Ok.
        /// </summary>
        internal static string Action_Status_Ok {
            get {
                return ResourceManager.GetString("Action.Status.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth.Srp.PublicData.OK.
        /// </summary>
        internal static string Auth_Srp_PublicData_OK {
            get {
                return ResourceManager.GetString("Auth.Srp.PublicData.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error(06570): bio need 18 years to return here..
        /// </summary>
        internal static string Bio_Missing_Default {
            get {
                return ResourceManager.GetString("Bio.Missing.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.Conn.Online.
        /// </summary>
        internal static string Database_Conn_Online {
            get {
                return ResourceManager.GetString("Database.Conn.Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.Conn.Unavailable.
        /// </summary>
        internal static string Database_Conn_Unavailable {
            get {
                return ResourceManager.GetString("Database.Conn.Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.Error.DataConsistency.
        /// </summary>
        internal static string Database_Error_DataConsistency {
            get {
                return ResourceManager.GetString("Database.Error.DataConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.Error.Internal.
        /// </summary>
        internal static string Internal_Server_Error {
            get {
                return ResourceManager.GetString("Internal.Server.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.Error.FailedAt.
        /// </summary>
        internal static string Log_Error_FailedAt {
            get {
                return ResourceManager.GetString("Log.Error.FailedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.VerifyAccount.SendFail.
        /// </summary>
        internal static string Mail_VerifyAccount_SendFail {
            get {
                return ResourceManager.GetString("Mail.VerifyAccount.SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.Mail.SendRatelimited.
        /// </summary>
        internal static string Mail_VerifyAccount_SendRatelimited {
            get {
                return ResourceManager.GetString("Mail.VerifyAccount.SendRatelimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.VerifyAccount.Title.
        /// </summary>
        internal static string Mail_VerifyAccount_Title {
            get {
                return ResourceManager.GetString("Mail.VerifyAccount.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.Error.RejectOperation.
        /// </summary>
        internal static string Request_Error_RejectOperation {
            get {
                return ResourceManager.GetString("Request.Error.RejectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.Error.NoInitialized.
        /// </summary>
        internal static string Response_Error_NoInitialized {
            get {
                return ResourceManager.GetString("Response.Error.NoInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Sttatus.Online.
        /// </summary>
        internal static string System_Sttatus_Online {
            get {
                return ResourceManager.GetString("System.Sttatus.Online", resourceCulture);
            }
        }
    }
}
