param(
    [Parameter(Mandatory = $true)]
    [string]$OutputDir,
    [Parameter(Mandatory = $true)]
    [string]$FallbackPath
)

$url = 'https://cdn.jsdelivr.net/gh/disposable-email-domains/disposable-email-domains@HEAD/disposable_email_blocklist.conf'

try {
    $content = (Invoke-WebRequest $url -TimeoutSec 10).Content
} catch {
    if ([string]::IsNullOrWhiteSpace($env:ALL_PROXY)) {
        $content = Get-Content $FallbackPath -Raw
    } elseif (Test-Path $FallbackPath) {
        $content = (Invoke-WebRequest $url -TimeoutSec 10).Content
    } else {
        throw "Neither remote nor local fallback available: $url"
    }
}

$lines = $content -split '\n' | ForEach-Object Trim | Where-Object { $_ -and $_ -notmatch '^#|^//' }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated/>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace backend.Utils;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('internal static partial class DisposableDomains')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    internal static readonly System.Collections.Frozen.FrozenSet<string> Domains =')
[void]$sb.Append('        System.Collections.Frozen.FrozenSet.ToFrozenSet<string>([')
$first = $true
foreach ($d in $lines) {
    if ($first) { $first = $false } else { [void]$sb.Append(',') }
    $escaped = $d.Replace('\', '\\').Replace('"', '\"')
    [void]$sb.Append('"').Append($escaped).Append('"')
}
[void]$sb.AppendLine(']);')
[void]$sb.AppendLine('}')

[void][System.IO.Directory]::CreateDirectory($OutputDir)
Set-Content (Join-Path $OutputDir 'DisposableDomains.g.cs') -Value $sb.ToString()
